# Settings
BROADCAST_INTERVAL = 2.0
CAMERAS_BROADCAST_MSG = b"ESP_DISCOVERY"
CAMERAS_BROADCAST_PORT = 12345
STREAM_PORT_RIGHT = 8080
STREAM_PORT_LEFT = 8081
CAMERAS = {
    STREAM_PORT_RIGHT: {"name": "RIGHT CAMERA", "side": "RIGHT"},
    STREAM_PORT_LEFT: {"name": "LEFT CAMERA", "side": "LEFT"},
}
CAMERA_TIMEOUT = 12.0

ROVER_BROADCAST_MSG = b"ROVER_DISCOVERY"
ROVER_BROADCAST_PORT = 4210
ROVER_CONTROL_PORT = 4211

FRAME_WIDTH = 240
FRAME_HEIGHT = 240

LEFT_IMAGE_FOLDER = "images/left"
RIGHT_IMAGE_FOLDER = "images/right"

# Websocket ports for different services
VIDEO_WEBSOCKET_PORT = 8765  # binary frames stream
CONTROL_WEBSOCKET_PORT = 8766  # JSON system status and command channel

FRAME_SEND_INTERVAL = 0.033  # ~30 FPS
STATUS_SEND_INTERVAL = 0.1  # how often to push system status (seconds)
